#!/bin/sh

# Get a list of staged ipynb files, excluding deleted files
files=$(git diff --diff-filter=d --name-only --cached *.ipynb)

if [[ -z $files ]]
then
  exit
fi

# Automatically remove output from staged changes beforecommitting
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $files

# Re-add the changed files so they're committed
git add $files
